// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnrrugfxgdpftgmsgzps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBucnJ1Z2Z4Z2RwZnRnbXNnenBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzA0MDMsImV4cCI6MjA3MjQ0NjQwM30.xl27jGDnVy4Dvc8j5GRyetjflpbvQEXqUII7U036KJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});